version: '3'
services:
    postgres:
        image: 'postgres:latest'
        environment:
         - POSTGRES_PASSWORD=postgres_password
         - POSTGRES_DB=simple-blog-api

    api:
        depends_on:
            - postgres
        image: thivyanagammai/simple_blog_api
        ports: 
            - '3000:3000'
        build: 
            context: ./
            dockerfile: Dockerfile
        environment:
            - POSTGRES_HOST=postgres
            - POSTGRES_PORT=5432
            - POSTGRES_USERNAME=postgres
            - POSTGRES_PASSWORD=postgres_password
            - POSTGRES_DB=simple-blog-api